version: '3'
services:
    web:
        build: . 
        ports:
            - "4001:3000" 
        volumes:
            - /app/node_module
            - .:/app
    tests: 
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_module
            - .:/app